version: '3'

services:
  gnps-plot-web:
    networks:
      - default
      - nginx-net
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: gnps-plot.ucsd.edu
      VIRTUAL_PORT: 5072
      LETSENCRYPT_HOST: gnps-plot.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net